name: midgard
description: A Flutter WebView app with native bottom navigation UI.
publish_to: "none" # Not for pub.dev
version: 1.0.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  webview_flutter: ^4.7.0    # WebView
  url_launcher: ^6.3.0
  share_plus: ^10.0.0
  package_info_plus: ^8.0.0
  provider: ^6.1.2
  connectivity_plus: ^6.0.3


  #cupertino_icons: ^1.0.6     # iOS icon pack (optional)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0       # Clean linting rules
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.0
  change_app_package_name: ^1.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"


flutter_native_splash:
  color: "#000000"       # background color while Flutter loads
  image: assets/images/fitted.png
  android_gravity: center
  android: true
  

  
  android_12:
    color: "#11181c"
    image: assets/images/fitted.png


flutter:

  uses-material-design: true

  assets:
    - assets/images/offline.png
    - assets/images/icon.png
    - assets/images/splash.png
    - assets/html/           # If using offline page support later
